---
collections:
  - name: infra.controller_configuration
  - name: chocolatey.chocolatey
  - name: community.windows
  - name: ansible.windows
  # Commented out until CI/CD can get fixed
  # - name: ansible.controller
  - name: awx.awx
...
