---
- name: Load a Controller via infra.
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  environment:
    CONTROLLER_HOST: "{{ controller_host }}"
    CONTROLLER_USERNAME: "{{ controller_username | default('admin') }}"
    CONTROLLER_PASSWORD: "{{ controller_password }}"
    CONTROLLER_VERIFY_SSL: "{{ controller_verify_ssl | default('true') }}"

  tasks:

    - name: Configure AAP2 Controller and Hub with resources
      when: controller_configuration_dispatcher_roles is defined
      block:

        - name: Create a new AAP2 Auth token using controller username/password
          awx.awx.token:
            description: Creating token to configure AAP2 resources
            scope: write
            state: present

        - name: Configure AAP2 Controller and Hub
          ansible.builtin.import_role:
            name: infra.controller_configuration.dispatch
