---
- name: Run Powershell script to enable RI
  hosts: win_machine
  gather_facts: false

  tasks:
    - name: Verify WinRM connection
      ansible.windows.win_ping:
      register: winrm_check

    - name: Print WinRM connection result
      ansible.builtin.debug:
        msg: "WinRM Connection: {{ winrm_check.msg }}"
      when: winrm_check.msg is defined

    - name: Stop playbook if WinRM connection fails
      ansible.builtin.fail:
        msg: "WinRM connection verification failed."
      when: not winrm_check.changed

    - name: Copy script to remote
      ansible.windows.win_copy:
        src: "query_services.ps1"
        dest: "{{ remote_dest }}"
      when: winrm_check.changed

    - name: Run Script
      ansible.windows.win_powershell:
        script: "{{ remote_dest }} -ServiceState {{ service_state }}"

    - name: Print output
      ansible.builtin.debug:
        var: ps_output
      when: winrm_check.changed

    - name: Send email notification on success
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_recipient }}"
        subject: "Ansible Playbook Successful"
        body: "The Ansible playbook ran successfully."
      failed_when: false

    - name: Send email notification on failure
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_recipient }}"
        subject: "Ansible Playbook Failed"
        body: "The Ansible playbook failed. Please check logs for details."
      failed_when: true
---
