- name: Run PowerShell script on Windows
  hosts: windows_machines_nc
  gather_facts: false
  tasks:
    - name: Ping the Windows machine
      win_ping:

    - name: Create destination directory
      win_shell: New-Item -ItemType Directory -Path C:\Temp -Force

    - name: Copy hello.ps1 script
      win_copy:
        src: "{{ playbook_dir }}/files/hello.ps1"
        dest: C:\Temp\test.ps1

    - name: Run the script
      win_shell: C:\temp\test.ps1

    - name: Verify script success
      win_shell: Get-Content C:\Temp\output.txt
      register: script_output
      ignore_errors: yes

    - debug:
        var: script_output.stdout_lines
      when: script_output.rc == 0

    - fail:
        msg: "Script did not run successfully"
      when: script_output.rc != 0 and "'Cannot find path" not in script_output.stderr
